[project]
enable_telemetry = true
user_env = []
session_timeout = 3600
user_session_timeout = 1296000  # 15 days
cache = false
allow_origins = ["*"]
[features.chat_history]
enabled = true
[features]
unsafe_allow_html = false
latex = false
user_message_autoscroll = true
auto_tag_thread = true
edit_message = true

[features.spontaneous_file_upload]
enabled = true
accept = ["*/*"]
max_files = 20
max_size_mb = 500

[features.audio]
sample_rate = 24000

[features.mcp.sse]
enabled = true

[features.mcp.stdio]
enabled = true
allowed_executables = ["npx", "uvx"]

[UI]
name = "Agentic Chainlit"
default_theme = "dark"
layout = "wide"
default_sidebar_state = "open"
description = "Customized Chainlit UI for testing JS/CSS injection"
cot = "full"

custom_css = "custom.css"
custom_css_attributes = 'media="all"'

custom_js = "custom.js"
custom_js_attributes = 'async type="module"'

[[UI.header_links]]
name = "Visit my github"
display_name = "Github"
icon_url = "https://github.githubassets.com/favicons/favicon.png"
url = "https://github.com/123Mismail"

[meta]
generated_by = "2.5.5"
